trigger:
  batch: true
  branches:
    include:
    - feature/*
    - release
    - main

pr:
- feature/*
- release
- main

stages:
- template: azure-pipelines/build-all.yml

- stage: Test
  displayName: Test
  dependsOn: []
  jobs:
  - template: azure-pipelines/test.yml
    parameters:
      jobName: Linux
      poolName: NetCore-Public
      demandsName: 1es-ubuntu-2004-open

  - template: azure-pipelines/test.yml
    parameters:
      jobName: Windows
      poolName: NetCore-Public
      demandsName: 1es-windows-2022-open

  - template: azure-pipelines/test.yml
    parameters:
      jobName: MacOS
      poolName: Azure Pipelines
      vmImageName: macOS-13

- stage: Test_OmniSharp
  displayName: Test OmniSharp
  dependsOn: []
  jobs:
  - job: Test
    strategy:
      matrix:
        linux:
          demandsName: 1es-ubuntu-2004-open
        windows:
          demandsName: 1es-windows-2022-open
    pool:
      name: NetCore-Public
      demands: ImageOverride -equals $(demandsName)
    steps:
    - template: azure-pipelines/test-omnisharp.yml
