trigger:
  branches:
    include:
    - main
    - prerelease
    - release
pr: none

variables:
  ${{ if eq(variables['Build.SourceBranchName'], 'release') }}:
    prereleaseFlag: ''
  ${{ else }}:
    prereleaseFlag: '--prerelease'

stages:
- stage: Build
  dependsOn: []
  jobs:
  - job: Build
    steps:
    - template: azure-pipelines/build.yml
      parameters:
        prereleaseFlag: $(prereleaseFlag)
    pool:
      name: NetCore1ESPool-Internal
      demands: ImageOverride -equals Build.Ubuntu.1804.Amd64

# TODO: add compliance, signing.