name: OmniSharp-VSCode CI

on:
  workflow_run:
      workflows: ["Update Fork and Apply Patches"]
      types:
        - completed
  workflow_dispatch:
    inputs:
      tags:
        description: 'Run this manually'
        required: false
        type: boolean
  # push:
  #   branches: [ main, feature/** ]

  # pull_request:
  #   branches: [ main, feature/** ]

jobs:
  build:
    if: ${{ github.event.workflow_run.conclusion == 'success' || github.event_name == 'workflow_dispatch' }}
    runs-on: ubuntu-latest
    timeout-minutes: 30

    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Setup dotnet
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '8.x'

    - name: Install Node.js 18.x
      uses: actions/setup-node@v3
      with:
        node-version: '18.x'
        registry-url: https://registry.npmjs.org/

    - name: Install dependencies
      run: |
          npm add tar
          npm add --save-dev @types/tar
          npm ci
          npm i -g gulp
    - name: Lint fix
      run: npx eslint ./ --fix
    - name: Compile
      run: npm run compile

    - name: Prepublish VSIXs
      run: npm run vscode:prepublish

    - name: Build VSIXs
      run: gulp 'vsix:release:package'




    - name: Upload build artifact (darwin-x64)
      id: upload-release-asset-darwin-x64
      uses: actions/upload-artifact@v3
      with:
        path: ./vsix/csharp-darwin-x64-*.vsix
        name: csharp-darwin-x64.vsix

    - name: Upload build artifact (linux-x64)
      id: upload-release-asset-linux-x64
      uses: actions/upload-artifact@v3
      with:
        path: ./vsix/csharp-linux-x64-*.vsix
        name: csharp-linux-x64.vsix

    - name: Upload build artifact (win32-x64)
      id: upload-release-asset-win32-x64
      uses: actions/upload-artifact@v3
      with:
        path: ./vsix/csharp-win32-x64-*.vsix
        name: csharp-win32-x64.vsix

    # - name: Upload build artifact (platform-neutral)
    #   uses: actions/upload-artifact@v3
    #   with:
    #     path: ./vsix/csharp-*.vsix
    #     name: csharp-platform-neutral.vsix