steps:
- checkout: self
  clean: true
  submodules: true
  fetchTags: false
  fetchDepth: 1

- template: prereqs.yml

- template: test-prereqs.yml

- script: npm run test
  displayName: 🧪 Run unit and integration tests
  env:
    DISPLAY: :99.0

- task: PublishPipelineArtifact@1
  condition: failed()
  displayName: 'Upload integration test logs'
  inputs:
    targetPath: '$(Build.SourcesDirectory)/.vscode-test/user-data/logs'
    artifactName: 'VSCode Test Logs ($(Agent.JobName)-$(System.JobAttempt))'
